"""delete_redundant_type_from_transaction

Revision ID: 8088c871a9aa
Revises: c1152151d758
Create Date: 2025-10-08 18:14:31.422481

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8088c871a9aa'
down_revision = 'c1152151d758'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_data', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', postgresql.ENUM('EXPENSE', 'INCOME', name='typeenum'), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
