"""initial

Revision ID: 9da79c9cc3a6
Revises: 
Create Date: 2025-09-23 13:40:38.989265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9da79c9cc3a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_data',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('category_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_data.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('EXPENSE', 'INCOME', name='typeenum'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category_data.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_data.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_data')
    op.drop_table('category_data')
    op.drop_table('user_data')
    # ### end Alembic commands ###
