"""correct_created_at

Revision ID: a487358f9922
Revises: 9da79c9cc3a6
Create Date: 2025-09-29 12:03:33.619538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a487358f9922'
down_revision = '9da79c9cc3a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     with op.batch_alter_table('user_data', schema=None) as batch_op:
        # Option A: it was integer seconds
          # Option A: it was integer seconds
         batch_op.alter_column(
        'user_data',
        'created_at',
        type_=sa.DateTime(timezone=True),
        server_default=sa.text('now()'),
        existing_nullable=False
    )
     op.execute("UPDATE user_data SET created_at = NOW() WHERE created_at IS NULL;")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_data', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
