"""change_name_of_date

Revision ID: c1152151d758
Revises: eff8ea452a3f
Create Date: 2025-10-08 15:26:19.541836

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c1152151d758'
down_revision = 'eff8ea452a3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('transaction_date')

    # ### end Alembic commands ###
