"""change_date_transaction

Revision ID: eff8ea452a3f
Revises: 7830a8abe62a
Create Date: 2025-10-08 15:11:01.492304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eff8ea452a3f'
down_revision = '7830a8abe62a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_data', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.INTEGER(),
               type_=sa.DateTime(),
               postgresql_using='to_timestamp(date)',
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_data', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DateTime(),
               type_=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
